### PR TITLE
Upgrade to 1.1.1 and upgrade SDK version

### LINKED ISSUE #4: Update runtime? Base SDK out of date
When updating from flathub, I get this message
```
Info: org.freedesktop.Platform//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. 
   Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.github.artemanufrij.regextester
```

Also, upstream is on v 1.1.1, and flathub is on 0.15. Hopefully a version bumb could occur as well.

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by Cogitri** [comment]
Not sure what we should do about that QA test when regextester doesn't offer >=64x64 icons

**Comment by kmoad** [comment]
I made a PR on upstream to fix the current build issues. Is there any way to do a test build against the PR before merging. I'd like to make sure it fixes all build issues, not just the current one.

**Comment by bilelmoussaoui** [comment]
> Not sure what we should do about that QA test when regextester doesn't offer >=64x64 icons

the icons are in svg, so you can just copy the icon to the scalable directory for now

**Comment by Cogitri** [comment]
Added the patch from !27

**Comment by Cogitri** [comment]
Works now :)

**Comment by bilelmoussaoui** [comment]
Thanks @Cogitri & @kmoad

**Pull request merged**
